# Generated by Django 5.1.5 on 2025-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures"),
        ),
    ]
